[tool.black]
line-length = 89
target-version = ['py311']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         
    | \.git          
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 89

[tool.flake8]
max-line-length = 89
extend-ignore = ["E203"]
max-complexity = 10

